version: "3.8"
services:
  app:
    # Build context should be the parent directory where the .devcontainer folder resides
    build:
      context: .. 
      dockerfile: .devcontainer/Dockerfile
    container_name: app-artifact
    volumes:
      # Mount the entire project directory into /workspace
      - ..:/workspace:cached
      # Persist bash history for the codespace user
      - ~/.bash_history:/home/codespace/.bash_history 
      # Persist data volume
      - artifactvirtual-data:/workspace/.data 
      # Mount Docker socket for Docker-in-Docker feature
      - /var/run/docker.sock:/var/run/docker-host.sock 
    # Keep the container running indefinitely
    command: sleep infinity 
    # Link to postgres service
    depends_on:
      - postgres
    # Expose ports (optional here, mainly controlled by devcontainer.json)
    # ports:
    #   - "7860:7860" 
    #   - "8888:8888"
    #   - "5000:5000"
    #   - "8501:8501"
    environment:
      # Example: Make database connection info available
      - DATABASE_URL=postgresql://artifact:virtual@postgres:5432/artifact_db
      # Ensure Ollama knows where to store models within the persistent volume
      - OLLAMA_MODELS=/workspace/.data/.ollama 

  postgres:
    image: postgres:15
    container_name: pg-artifact
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: artifact
      POSTGRES_PASSWORD: virtual
      POSTGRES_DB: artifact_db
    volumes:
      # Use a named volume for persistent PostgreSQL data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  artifactvirtual-data:
